# Generated by Django 5.2.8 on 2025-11-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('cover_image', models.ImageField(upload_to='covers/')),
            ],
        ),
        migrations.CreateModel(
            name='EBookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers_images', to='ebook.ebook')),
            ],
        ),
    ]
