# Generated by Django 5.0.1 on 2025-11-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_ebookcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
