# Generated by Django 5.2.8 on 2025-11-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
