# Generated by Django 5.2.8 on 2025-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_ebookcategory_ebook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
