# Generated by Django 5.2.8 on 2025-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_ebook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
